### ISSUE TITLE
Opensearch: certificate error during Orborus connection

### ISSUE THREAD

**Issue by JonasCir** [Shuffle/Shuffle#1110]
**Describe the bug**

When running the latest version of the `docker-compose` deployment, the `shuffle-opensearch` container will repeatedly complain about an "exception during establishing a SSL connection" with 
`shuffle-orborus`.

**To Reproduce**

1. Run installation: I did the steps described [here](https://github.com/Shuffle/Shuffle/blob/main/.github/install-guide.md#docker---nix)
2. Changes in `.env`: Set `SHUFFLE_DEFAULT_USERNAME`, `SHUFFLE_DEFAULT_PASSWORD`, and `SHUFFLE_ENCRYPTION_MODIFIER`
3. Start and wait
4. Login
5. Go to Apps and force sync/download everything
6. Create new workflow: Run a vanilla schedule every 10 seconds with an `Shuffle Tools` action which repeats back to me the `$exec` parameter
7. Look at the docker logs: The following will happen repeatedly:
```text
shuffle-backend     | 2023/05/19 13:16:09 [DEBUG] Got workflow result from 172.22.0.3:46706 of length 17284.
shuffle-backend     | 2023/05/19 13:16:09 [INFO][599d1f65-47eb-446a-8f88-348d3c7adf08] Set workflowexecution based on new worker (>0.8.53) for workflow e717970e-b705-423e-9f37-723d94ae5154. Actions: 1, Triggers: 1, Results: 1, Status: FINISHED
shuffle-backend     | 2023/05/19 13:16:09 [DEBUG] Got workflow result from 172.22.0.3:46706 of length 17284.
shuffle-backend     | 2023/05/19 13:16:09 [INFO] Already finished (set workflow)! Stopping the rest of the request for execution 599d1f65-47eb-446a-8f88-348d3c7adf08.
shuffle-backend     | 2023/05/19 13:16:09 [INFO][599d1f65-47eb-446a-8f88-348d3c7adf08] Set workflowexecution based on new worker (>0.8.53) for workflow e717970e-b705-423e-9f37-723d94ae5154. Actions: 1, Triggers: 1, Results: 1, Status: FINISHED
shuffle-backend     | 2023/05/19 13:16:37 [INFO] Running POST execution with body of length 145 for workflow e717970e-b705-423e-9f37-723d94ae5154
shuffle-backend     | 2023/05/19 13:16:37 [DEBUG][] Body len: 145
shuffle-backend     | 2023/05/19 13:16:37 [INFO] Should start execution on node a7866b8e-7c92-4a7b-9448-936d240e326c
shuffle-backend     | 2023/05/19 13:16:37 [INFO] Execution source is schedule for execution ID 2bf05922-b097-42c0-98b1-a540b9fc8bd3 in workflow e717970e-b705-423e-9f37-723d94ae5154. Organization: 0485e018-5111-4ad1-ba94-759b6ed0ceca
shuffle-backend     | 2023/05/19 13:16:37 [INFO][2bf05922-b097-42c0-98b1-a540b9fc8bd3] Validation. Status: EXECUTING, Actions: 1, Extra: 0, Results: 0
shuffle-backend     | 2023/05/19 13:16:37 [INFO] Execution: 2bf05922-b097-42c0-98b1-a540b9fc8bd3 should execute onprem with execution environment "Shuffle". Workflow: e717970e-b705-423e-9f37-723d94ae5154
shuffle-orborus     | 2023/05/19 13:16:38 [INFO] Worker Container 5fc5499cce153336333b71cb7cc8c0b322ed050599267e8abf67c2cb9187ad10 was created under environment Shuffle: docker logs 5fc5499cce153336333b71cb7cc8c0b322ed050599267e8abf67c2cb9187ad10
shuffle-opensearch  | [2023-05-19T13:16:38,251][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [shuffle-opensearch] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
shuffle-opensearch  | javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
shuffle-opensearch  | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:358) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
shuffle-opensearch  | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at java.lang.Thread.run(Thread.java:833) [?:?]
shuffle-opensearch  | [2023-05-19T13:16:38,252][WARN ][o.o.h.AbstractHttpServerTransport] [shuffle-opensearch] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/172.22.0.2:9200, remoteAddress=/172.22.0.3:35830}
shuffle-opensearch  | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at java.lang.Thread.run(Thread.java:833) [?:?]
shuffle-opensearch  | Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
shuffle-opensearch  | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:358) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
shuffle-opensearch  | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
shuffle-opensearch  | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
shuffle-opensearch  | 	... 16 more

```

Every time the the `shuffle-orborus` container creates the creation of a  worker container under the Shuffle environment, the opensearch container will complain about a bad certificate (note that the mentioned remote IP address in the connection closed is `172.22.0.3` which is assigned to the `orborus` container).

**Expected behavior**

Standard setup and the mentioned simple workflow executes repeatedly without errors being logged.

**Comment by frikky** [comment]
Hey!

We saw this as well - Orborus shouldn't connect but in the default stack it still does. This has no consequence outside of extra load on Opensearch itself. 

Thanks :)

**Comment by JonasCir** [comment]
Alright thank you for the swift response (and for creating this great peace of software of course :)
