### ISSUE TITLE
Unable to start shuffle after installing on ubuntu 22.04

### ISSUE THREAD

**Issue by yonz2** [Shuffle/Shuffle#884]
**Describe the bug**
After a fresh install on ubuntu 22.04, running docker desktop version 20.10.17 / Compose version 2.6.0, I am unable to start shuffle.

There seem to be an issue with the uid/gid inside of the container. If I peek inside the container the uid/gid of the `data` directory is set to `0:0 (root:root)`, not `1000:1000 (opensearch:opensearch)` as I would have expected.

**To Reproduce**
1. Run installation standard installation
2. Note that the `shuffle-database` directory will not be created

...

**Expected behavior**
That the `shuffle-database` directory will be created and files copied to it (albeit with the wrong uid/gid, that would then be changed with the` sudo chown -R 1000:1000 ./shuffle-database` step, as described in the installation guide.

**Docker Version**
```
Docker version 20.10.17, build 100c701

Docker Compose version v2.6.0
```

**Docker containers running**
```
docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                      PORTS                                                  NAMES
cd7d63c24f4d   ghcr.io/frikky/shuffle-frontend:latest   "/entrypoint.sh ngin…"   15 minutes ago   Up 9 minutes                0.0.0.0:3001->80/tcp, 0.0.0.0:3443->443/tcp            shuffle-frontend
472a6b27d935   ghcr.io/frikky/shuffle-backend:latest    "./webapp"               15 minutes ago   Up 9 minutes                0.0.0.0:5001->5001/tcp                                 shuffle-backend
e3d6bdca2583   opensearchproject/opensearch:1.2.4       "./opensearch-docker…"   15 minutes ago   Up 9 minutes                9300/tcp, 9600/tcp, 0.0.0.0:9200->9200/tcp, 9650/tcp   shuffle-opensearch
27700bd7a115   ghcr.io/frikky/shuffle-orborus:latest    "./orborus"              15 minutes ago   Up 9 minutes                                                                       shuffle-orborus
```

**Docker Images in use**
```
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
frikky/shuffle                    app_sdk   5ebacd8d4eb6   4 weeks ago     292MB
ghcr.io/frikky/shuffle-frontend   latest    685dcf8ac6a2   7 weeks ago     185MB
ghcr.io/frikky/shuffle-worker     latest    422cf8d5bf3b   7 weeks ago     44.3MB
ghcr.io/frikky/shuffle-backend    latest    91e830aa774b   7 weeks ago     53.6MB
ghcr.io/frikky/shuffle-orborus    latest    a717e06ff627   7 weeks ago     29.1MB
opensearchproject/opensearch      1.2.4     6842d435e62e   4 months ago    827MB
ghcr.io/frikky/shuffle-app_sdk    0.8.97    4cb8d9788646   12 months ago   44.8MB
```

**Logs from the shuffle-opeansearch container**
```
docker logs shuffle-opensearch:

Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-1.2.4
Detected OpenSearch Security Version: 1.2.4.0

### Success
### Execute this script now on all your nodes and then start all nodes
### OpenSearch Security will be automatically initialized.
### If you like to change the runtime configuration 
### change the files in ../securityconfig and execute: 
"/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh" -cd "/usr/share/opensearch/plugins/opensearch-security/securityconfig" -icl -key "/usr/share/opensearch/config/kirk-key.pem" -cert "/usr/share/opensearch/config/kirk.pem" -cacert "/usr/share/opensearch/config/root-ca.pem" -nhnv
### or run ./securityadmin_demo.sh
### To use the Security Plugin ConfigurationGUI
### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
Enabling OpenSearch Security Plugin
[2022-06-20T22:10:41,828][INFO ][o.o.n.Node               ] [shuffle-opensearch] version[1.2.4], pid[101], build[tar/e505b10357c03ae8d26d675172402f2f2144ef0f/2022-01-14T03:38:06.881862Z], OS[Linux/5.10.104-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
[2022-06-20T22:10:41,829][INFO ][o.o.n.Node               ] [shuffle-opensearch] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]
[2022-06-20T22:10:41,829][INFO ][o.o.n.Node               ] [shuffle-opensearch] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-6643570708861532536, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy, -Dopensearch.cgroups.hierarchy.override=/, -Xms1024m, -Xmx1024m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2022-06-20T22:10:42,456][INFO ][o.o.s.s.t.SSLConfig      ] [shuffle-opensearch] SSL dual mode is disabled
[2022-06-20T22:10:42,456][INFO ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] OpenSearch Config path is /usr/share/opensearch/config
[2022-06-20T22:10:42,618][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] JVM supports TLSv1.3
[2022-06-20T22:10:42,619][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] Config directory is /usr/share/opensearch/config/, from there the key- and truststore files are resolved relatively
[2022-06-20T22:10:42,840][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] TLS Transport Client Provider : JDK
[2022-06-20T22:10:42,840][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] TLS Transport Server Provider : JDK
[2022-06-20T22:10:42,840][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] TLS HTTP Provider             : JDK
[2022-06-20T22:10:42,840][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2, TLSv1.1]
[2022-06-20T22:10:42,840][INFO ][o.o.s.s.DefaultSecurityKeyStore] [shuffle-opensearch] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2, TLSv1.1]
[2022-06-20T22:10:42,977][INFO ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] Clustername: shuffle-cluster
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] Directory /usr/share/opensearch/config has insecure file permissions (should be 0700)
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] File /usr/share/opensearch/config/esnode.pem has insecure file permissions (should be 0600)
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] File /usr/share/opensearch/config/esnode-key.pem has insecure file permissions (should be 0600)
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] File /usr/share/opensearch/config/kirk.pem has insecure file permissions (should be 0600)
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] File /usr/share/opensearch/config/root-ca.pem has insecure file permissions (should be 0600)
[2022-06-20T22:10:42,980][WARN ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] File /usr/share/opensearch/config/kirk-key.pem has insecure file permissions (should be 0600)
[2022-06-20T22:10:43,052][INFO ][o.o.p.c.PluginSettings   ] [shuffle-opensearch] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
[2022-06-20T22:10:43,349][INFO ][o.o.i.r.ReindexPlugin    ] [shuffle-opensearch] ReindexPlugin reloadSPI called
[2022-06-20T22:10:43,349][INFO ][o.o.i.r.ReindexPlugin    ] [shuffle-opensearch] Unable to find any implementation for RemoteReindexExtension
[2022-06-20T22:10:43,357][INFO ][o.o.j.JobSchedulerPlugin ] [shuffle-opensearch] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
[2022-06-20T22:10:43,359][INFO ][o.o.j.JobSchedulerPlugin ] [shuffle-opensearch] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
[2022-06-20T22:10:43,373][INFO ][o.o.j.JobSchedulerPlugin ] [shuffle-opensearch] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [aggs-matrix-stats]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [analysis-common]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [geo]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [ingest-common]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [ingest-geoip]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [ingest-user-agent]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [lang-expression]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [lang-mustache]
[2022-06-20T22:10:43,374][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [lang-painless]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [mapper-extras]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [opensearch-dashboards]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [parent-join]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [percolator]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [rank-eval]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [reindex]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [repository-url]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded module [transport-netty4]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-alerting]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-anomaly-detection]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-asynchronous-search]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-cross-cluster-replication]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-index-management]
[2022-06-20T22:10:43,375][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-job-scheduler]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-knn]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-observability]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-performance-analyzer]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-reports-scheduler]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-security]
[2022-06-20T22:10:43,376][INFO ][o.o.p.PluginsService     ] [shuffle-opensearch] loaded plugin [opensearch-sql]
[2022-06-20T22:10:43,389][INFO ][o.o.s.OpenSearchSecurityPlugin] [shuffle-opensearch] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in opensearch.yml
[2022-06-20T22:10:43,396][DEPRECATION][o.o.d.c.s.Settings       ] [shuffle-opensearch] [node.max_local_storage_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
[2022-06-20T22:10:43,402][INFO ][o.o.e.NodeEnvironment    ] [shuffle-opensearch] using [1] data paths, mounts [[/usr/share/opensearch/data (none)]], net usable_space [893.5gb], net total_space [903.3gb], types [virtiofs]
[2022-06-20T22:10:43,402][INFO ][o.o.e.NodeEnvironment    ] [shuffle-opensearch] heap size [1gb], compressed ordinary object pointers [true]
[2022-06-20T22:10:43,440][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [shuffle-opensearch] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: OpenSearchException[failed to bind service]; nested: IOException[failed to test writes in data directory [/usr/share/opensearch/data/nodes/0] write permission is required]; nested: AccessDeniedException[/usr/share/opensearch/data/nodes/0/.opensearch_temp_file];
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.4.jar:1.2.4]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.4.jar:1.2.4]
Caused by: org.opensearch.OpenSearchException: failed to bind service
	at org.opensearch.node.Node.<init>(Node.java:965) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.4.jar:1.2.4]
	... 6 more
Caused by: java.io.IOException: failed to test writes in data directory [/usr/share/opensearch/data/nodes/0] write permission is required
	at org.opensearch.env.NodeEnvironment.tryWriteTempFile(NodeEnvironment.java:1298) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.env.NodeEnvironment.assertCanWrite(NodeEnvironment.java:1261) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:343) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.4.jar:1.2.4]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.4.jar:1.2.4]
	... 6 more

```
**Peek inside the container**
```
sh-4.2$ ls -ln
total 305
-rw-r--r--  1 1000 1000  11358 Jan 14 03:35 LICENSE.txt
-rw-r--r--  1 1000 1000 215355 Jan 14 03:42 NOTICE.txt
-rw-r--r--  1 1000 1000   1761 Jan 14 03:35 README.md
drwxr-xr-x  2 1000 1000   4096 Jan 14 03:58 bin
drwxr-xr-x  1 1000 1000   4096 Jun 20 22:10 config
drwxrwxrwx  3    0    0      7 Jun 20 21:45 data
drwxr-xr-x  9 1000 1000   4096 Jan 14 03:43 jdk
drwxr-xr-x  3 1000 1000   4096 Jan 14 03:43 lib
drwxr-xr-x  1 1000 1000   4096 Jun 20 22:16 logs
-rw-r--r--  1 1000 1000   4414 Jan 14 03:59 manifest.yml
drwxr-xr-x 19 1000 1000   4096 Jan 14 03:43 modules
-rwxr-xr-x  1 1000 1000   5396 Feb 14 19:13 opensearch-docker-entrypoint.sh
-rwxr-xr-x  1 1000 1000   2171 Feb 14 19:13 opensearch-onetime-setup.sh
-rwxr-xr-x  1 1000 1000   2445 Jan 14 03:58 opensearch-tar-install.sh
drwxr-xr-x  6 1000 1000   4096 Jan 14 03:58 performance-analyzer-rca
drwxr-xr-x  1 1000 1000   4096 Jan 14 03:59 plugins
-rwxrwxr-x  1 1000 1000    315 Jun 20 22:10 securityadmin_demo.sh

```

**Comment by yonz2** [comment]
However ... If I make the directory "world writeable" with `chmod -R 777 shuffle-database/` it works

```
yonz@hulda:~/Shuffle$ ls -lan shuffle-database/
total 47
drwxrwxrwx 3   1000   1000  7 Jun 21 22:11 .
drwxrwxr-x 9   1000   1000 18 Jun 21 21:49 ..
-rw-rw-r-- 1 100999 100999  5 Jun 21 22:11 batch_metrics_enabled.conf
-rw-rw-r-- 1 100999 100999  5 Jun 21 22:11 logging_enabled.conf
drwxrwxr-x 3 100999 100999  3 Jun 21 22:11 nodes
-rw-rw-r-- 1 100999 100999  5 Jun 21 22:11 performance_analyzer_enabled.conf
-rw-rw-r-- 1 100999 100999  5 Jun 21 22:11 rca_enabled.conf
```
The uid/gid are still strange, but I'm able to login to shuffle


Yonz

**Comment by yonz2** [comment]
With "777" the Shuffle starts
